import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Introduction',
    },
    {
      type: 'category',
      label: '📚 Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'getting-started/overview',
        'getting-started/prerequisites',
        'getting-started/hardware-requirements',
        'getting-started/software-setup',
      ],
    },
    {
      type: 'category',
      label: '🤖 Module 1: ROS 2',
      collapsible: true,
      collapsed: true,
      items: [
        'module-1/introduction',
        'module-1/ros2-architecture',
        'module-1/nodes-and-topics',
        'module-1/services-and-actions',
        'module-1/urdf-robot-description',
        'module-1/rclpy-python-integration',
        'module-1/launch-files',
        'module-1/project-ros2-package',
      ],
    },
    {
      type: 'category',
      label: '🎮 Module 2: Gazebo & Unity',
      collapsible: true,
      collapsed: true,
      items: [
        'module-2/introduction',
        'module-2/gazebo-fundamentals',
        'module-2/physics-simulation',
        'module-2/sensor-simulation',
        'module-2/unity-integration',
        'module-2/urdf-sdf-formats',
        'module-2/environment-building',
        'module-2/project-simulated-robot',
      ],
    },
    {
      type: 'category',
      label: '🧠 Module 3: NVIDIA Isaac',
      collapsible: true,
      collapsed: true,
      items: [
        'module-3/introduction',
        'module-3/isaac-sim-overview',
        'module-3/synthetic-data-generation',
        'module-3/isaac-ros-hardware-acceleration',
        'module-3/vslam-navigation',
        'module-3/nav2-path-planning',
        'module-3/perception-pipeline',
        'module-3/reinforcement-learning',
        'module-3/sim-to-real-transfer',
        'module-3/project-perception-system',
      ],
    },
    {
      type: 'category',
      label: '🗣️ Module 4: VLA',
      collapsible: true,
      collapsed: true,
      items: [
        'module-4/introduction',
        'module-4/voice-to-action-whisper',
        'module-4/llm-cognitive-planning',
        'module-4/natural-language-commands',
        'module-4/multimodal-interaction',
        'module-4/gpt-integration',
        'module-4/conversational-robotics',
        'module-4/project-autonomous-humanoid',
      ],
    },
    {
      type: 'category',
      label: '🦾 Humanoid Development',
      collapsible: true,
      collapsed: true,
      items: [
        'humanoid/kinematics-dynamics',
        'humanoid/bipedal-locomotion',
        'humanoid/balance-control',
        'humanoid/manipulation-grasping',
        'humanoid/human-robot-interaction',
      ],
    },
    {
      type: 'category',
      label: '🎯 Capstone Project',
      collapsible: true,
      collapsed: true,
      items: [
        'capstone/project-overview',
        'capstone/requirements',
        'capstone/architecture-design',
        'capstone/implementation-guide',
        'capstone/testing-validation',
        'capstone/presentation-tips',
      ],
    },
    {
      type: 'category',
      label: '📖 Appendices',
      collapsible: true,
      collapsed: true,
      items: [
        'appendix/glossary',
        'appendix/resources',
        'appendix/troubleshooting',
        'appendix/hardware-guide',
      ],
    },
  ],
};

export default sidebars;